3 recipe details
Dogggo/cook-it pull request #3
Opened 2022-10-01 11:19 UTC by Dogggo

2022-10-14 12:48 UTC, DominikKalinowski requested changes

2022-10-14 12:48 UTC, DominikKalinowski commented on libs/recipies/feature-recipe-details/src/lib/recipe-details/recipe-details.component.html
> +<cook-it-recipe-overview [recipe]="(recipe$ | async)!"></cook-it-recipe-overview>
It will reduce the "!"  which is unsafe

2022-10-14 12:48 UTC, DominikKalinowski commented on libs/recipies/shared/src/lib/format-time.pipe.ts
> +      return value < 10 ? `0h : 0${value}m` : `0h : ${value}m`;
it seems little to complicated

2022-10-14 12:48 UTC, DominikKalinowski commented on libs/recipies/shared/src/lib/format-time.pipe.ts
> +}
```suggestion
  transform(timeInMinutes: number): string {
    const hours = Math.floor(timeInMinutes / 60);
    const minutes = timeInMinutes % 60;
    return `${hours}h : ${String(minutes).padStart(2, '0')}m`;
  }
```

2022-10-14 12:48 UTC, DominikKalinowski commented on libs/recipies/shared/src/lib/format-time.pipe.ts
> +  name: 'formatTime',
make it standalone

2022-10-14 12:48 UTC, DominikKalinowski commented on libs/recipies/feature-recipe-list/src/lib/sidenav/sidenav.component.ts
> +import * as recipeDetailsComponent from 'libs/recipies/feature-recipe-details/src/lib/recipe-details/recipe-details.component';
```suggestion
import { recipeDetailsComponent } from '@recipies/feature-recipe-details';
```

2022-11-07 13:29 UTC, Dogggo commented on libs/recipies/feature-recipe-list/src/lib/sidenav/sidenav.component.ts
> +import * as recipeDetailsComponent from 'libs/recipies/feature-recipe-details/src/lib/recipe-details/recipe-details.component';
its not working, maybe i did something wrong with imports / exports? error says that module cannot be found

2022-11-07 13:32 UTC, Dogggo commented on libs/recipies/data-access/src/lib/+state/recipies.effects.ts
> +
Its an effect for changing current selectedId

2022-11-09 09:29 UTC, DominikKalinowski requested changes

2022-11-09 09:29 UTC, DominikKalinowski commented on libs/recipies/feature-recipe-details/src/lib/recipe-details/recipe-details.component.ts
>    ngOnDestroy(): void {
untilDestoryed is making that

2022-11-09 09:29 UTC, DominikKalinowski commented on libs/recipies/feature-recipe-details/src/lib/recipe-details/recipe-details.component.ts
> +      untilDestroyed(this),
untilDestroyed should be the last operator in pipe

2022-11-09 09:29 UTC, DominikKalinowski commented on libs/recipies/data-access/src/lib/+state/recipies.effects.ts
>    })
what is select$ and what's doing this logic in pipe? 🤔

2022-11-09 09:29 UTC, DominikKalinowski commented on libs/recipies/feature-recipe-details/src/lib/recipe-details/recipe-details.component.ts
> +  changeSelectedRecipe() {
could be private

2022-11-09 09:29 UTC, DominikKalinowski commented on libs/recipies/feature-recipe-details/src/lib/recipe-details/recipe-details.component.ts
> +      this.recipe$ = this.store.select(getSelected);
there is no need to update selector this.recipe$, this assign can be done when recipe$ is declared

2022-11-21 00:29 UTC, Dogggo commented on libs/recipies/data-access/src/lib/+state/recipies.effects.ts
>    })
select can set id of currently selected recipe

2023-02-01 09:48 UTC, DominikKalinowski commented on libs/recipies/data-access/src/lib/+state/recipies.effects.ts
> +
to register observable as an effect you should wrap it with createEffect function, same as you did for init$ effect

2023-02-01 09:50 UTC, DominikKalinowski commented on libs/recipies/data-access/src/lib/+state/recipies.effects.ts
> +
and also this effect doesn't do anything, it listen for selectRecipe actions and it dispatch the same action as a result

2023-02-01 09:59 UTC, DominikKalinowski commented on libs/recipies/feature-recipe-list/src/lib/sidenav/sidenav.component.ts
> +import * as recipeDetailsComponent from 'libs/recipies/feature-recipe-details/src/lib/recipe-details/recipe-details.component';
yes, to make something exported from that lib you should export it it the index.ts in that lib

2023-02-01 10:01 UTC, DominikKalinowski commented on libs/recipies/feature-recipe-list/src/lib/sidenav/sidenav.component.ts
> +import * as recipeDetailsComponent from 'libs/recipies/feature-recipe-details/src/lib/recipe-details/recipe-details.component';
and also the lib name is little different - @cook-it/recipies/feature-recipe-details, my mistake

2023-02-06 09:23 UTC, closed without merging