4 add,edit,delete recipe
Dogggo/cook-it pull request #4
Opened 2022-10-13 22:14 UTC by Dogggo

2022-10-14 14:25 UTC, DominikKalinowski requested changes

2022-10-14 14:25 UTC, DominikKalinowski commented on libs/recipies/feature-edit-recipe/src/lib/edit-recipe/edit-recipe.component.html
> +      <button class="delete-button" mat-button (click)="deleteIngredient(i)">
use delete button directly in the IngredientForm (not pass it through ng-content), and emit delete event by output

2022-10-14 14:25 UTC, DominikKalinowski commented on libs/recipies/feature-edit-recipe/src/lib/edit-recipe/edit-recipe.component.ts
> +    });
move to separate method

2022-10-14 14:25 UTC, DominikKalinowski commented on libs/recipies/feature-edit-recipe/src/lib/edit-recipe/edit-recipe.component.ts
> +    this.recipe$.pipe(take(1)).subscribe((recipe) => {
```suggestion
    this.recipe$.pipe(first()).subscribe((recipe) => {
```

2022-10-14 14:25 UTC, DominikKalinowski commented on libs/recipies/feature-edit-recipe/src/lib/edit-recipe/edit-recipe.component.ts
> +  public addIngredient() {
by convention we don't use public keyword, it's public by default

2022-10-14 14:25 UTC, DominikKalinowski commented on libs/recipies/feature-recipe-details/src/lib/recipe-details/recipe-details.component.ts
> +  recipe?: RecipiesEntity;
subscribe in the template instead, and not keep separate recipe property here

2022-10-14 14:25 UTC, DominikKalinowski commented on libs/recipies/feature-recipe-list/src/lib/guard/form/form.guard.ts
> +    return of(true);
it can return just true

2022-10-14 14:25 UTC, DominikKalinowski commented on libs/recipies/feature-recipe-list/src/lib/guard/form/form.guard.ts
> +  constructor(public dialog: MatDialog) {}
do you need dialog here?

2022-10-14 14:25 UTC, DominikKalinowski commented on libs/recipies/feature-recipe-list/src/lib/guard/recipes/recipes.guard.ts
> +      take(1)
```suggestion
      first(Boolean)
```

2022-10-14 14:25 UTC, DominikKalinowski commented on libs/recipies/feature-recipe-list/src/lib/sidenav/sidenav.component.html
> +      <div style="position: sticky; bottom: 0; z-index: 1; opacity: 100%">
use class instead

2022-10-14 14:25 UTC, DominikKalinowski commented on libs/recipies/feature-recipe-list/src/lib/guard/form/form.guard.ts
> +export class FormGuard implements CanDeactivate<unknown> {
type it better than unknown ;)

2022-10-14 14:25 UTC, DominikKalinowski commented on libs/recipies/ui-recipe-form/src/lib/ingredient-form/ingredient-form.component.html
> +<div class="container">
is this container div really needed?

2022-11-07 12:38 UTC, Dogggo commented on libs/recipies/data-access/src/lib/+state/recipies.effects.ts
> +        return this.recipiesService.editRecipe(action.payload, action.id).pipe(
In heroku app there is no navigation to the details page after editing

2022-11-07 12:46 UTC, Dogggo commented on libs/recipies/data-access/src/lib/+state/recipies.reducer.ts
> +    loaded: false,
because loaded is set to true when given action has succeed

2022-11-07 12:57 UTC, Dogggo commented on libs/recipies/feature-recipe-details/src/lib/recipe-details/recipe-details.component.ts
> +  recipe?: RecipiesEntity;
but i need recipe name property in "deleteRecipeConfirmation" method

2023-02-01 14:28 UTC, DominikKalinowski commented on libs/recipies/feature-edit-recipe/src/lib/edit-recipe/edit-recipe.component.html
> +              : 'container__button-save'
why we need this classes?

2023-02-01 14:28 UTC, DominikKalinowski commented on libs/recipies/feature-edit-recipe/src/lib/edit-recipe/edit-recipe.component.html
> +          "
same here

2023-02-02 08:56 UTC, DominikKalinowski submitted a review, later dismissed

2023-02-02 09:58 UTC, DominikKalinowski approved these changes

2023-02-02 09:59 UTC, merged